//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikWpfApp2.SmartIPWebRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartIPWebRef.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmsRequest", ReplyAction="*")]
        TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse XmsRequest(TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmsRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse> XmsRequestAsync(TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmsRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmsRequest", Namespace="http://tempuri.org/", Order=0)]
        public TelerikWpfApp2.SmartIPWebRef.XmsRequestRequestBody Body;
        
        public XmsRequestRequest() {
        }
        
        public XmsRequestRequest(TelerikWpfApp2.SmartIPWebRef.XmsRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmsRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestData;
        
        public XmsRequestRequestBody() {
        }
        
        public XmsRequestRequestBody(string requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmsRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmsRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public TelerikWpfApp2.SmartIPWebRef.XmsRequestResponseBody Body;
        
        public XmsRequestResponse() {
        }
        
        public XmsRequestResponse(TelerikWpfApp2.SmartIPWebRef.XmsRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmsRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object XmsRequestResult;
        
        public XmsRequestResponseBody() {
        }
        
        public XmsRequestResponseBody(object XmsRequestResult) {
            this.XmsRequestResult = XmsRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : TelerikWpfApp2.SmartIPWebRef.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<TelerikWpfApp2.SmartIPWebRef.SmsSoap>, TelerikWpfApp2.SmartIPWebRef.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse TelerikWpfApp2.SmartIPWebRef.SmsSoap.XmsRequest(TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest request) {
            return base.Channel.XmsRequest(request);
        }
        
        public object XmsRequest(string requestData) {
            TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest inValue = new TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest();
            inValue.Body = new TelerikWpfApp2.SmartIPWebRef.XmsRequestRequestBody();
            inValue.Body.requestData = requestData;
            TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse retVal = ((TelerikWpfApp2.SmartIPWebRef.SmsSoap)(this)).XmsRequest(inValue);
            return retVal.Body.XmsRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse> TelerikWpfApp2.SmartIPWebRef.SmsSoap.XmsRequestAsync(TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest request) {
            return base.Channel.XmsRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelerikWpfApp2.SmartIPWebRef.XmsRequestResponse> XmsRequestAsync(string requestData) {
            TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest inValue = new TelerikWpfApp2.SmartIPWebRef.XmsRequestRequest();
            inValue.Body = new TelerikWpfApp2.SmartIPWebRef.XmsRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((TelerikWpfApp2.SmartIPWebRef.SmsSoap)(this)).XmsRequestAsync(inValue);
        }
    }
}
